### ISSUE TITLE
Missing headers

### ISSUE THREAD

**Issue by bbrrck** [avaxman/Directional#2]
Hi Amir, when compiling the examples and the tutorial 302_PolyVectors, I get the error about missing `drawable_field.h` and `draw_singularities.h`. Are these headers going to be included anytime soon? Thanks!

**Comment by bbrrck** [comment]
Same goes for the tutorial 202_Sampling,  with an additional missing member `field_draw_flags`.

**Comment by avaxman** [comment]
Hi Tibor,

The tutorial is currently in construction (note it's not yet documented entirely) with the library in refactoring. For instance, drawable_field.h and draw_singularities.h don't exist anymore. However, since I revised the code much, the examples wouldn't work either; it's gonna change very soon, hopefully by the end of the week. Chapter 1 of the tutorial works, for instance. I'll keep you posted.

**Comment by bbrrck** [comment]
Looking forward to that. Let me know if there's anything I can help with.

**Comment by avaxman** [comment]
Everything should be consistent now. Check out the new tutorial!
